### ISSUE TITLE
Error for pip install python-djvulibre

### ISSUE THREAD

**Issue by matthewstidham** [jwilk/python-djvulibre#12]
Building wheel for python-djvulibre (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/matthew/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8xjtabd6/python-djvulibre/setup.py'"'"'; __file__='"'"'/tmp/pip-install-8xjtabd6/python-djvulibre/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-dxswz14q --python-tag cp37
       cwd: /tmp/pip-install-8xjtabd6/python-djvulibre/
  Complete output (45 lines):
  pkg-config failed: Package ddjvuapi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `ddjvuapi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'ddjvuapi' found
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/djvu
  copying djvu/__init__.py -> build/lib.linux-x86_64-3.7/djvu
  copying djvu/const.py -> build/lib.linux-x86_64-3.7/djvu
  copying djvu/dllpath.py -> build/lib.linux-x86_64-3.7/djvu
  running build_ext
  pkg-config failed: Package ddjvuapi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `ddjvuapi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'ddjvuapi' found
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-8xjtabd6/python-djvulibre/setup.py", line 321, in <module>
      distutils.core.setup(**setup_params)
    File "/home/matthew/anaconda3/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/matthew/anaconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/home/matthew/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/matthew/anaconda3/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/home/matthew/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/matthew/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/matthew/anaconda3/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/matthew/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/matthew/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-8xjtabd6/python-djvulibre/setup.py", line 174, in run
      djvulibre_version = get_djvulibre_version()
    File "/tmp/pip-install-8xjtabd6/python-djvulibre/setup.py", line 140, in get_djvulibre_version
      raise RuntimeError('cannot determine DjVuLibre version')
  RuntimeError: cannot determine DjVuLibre version
  ----------------------------------------
  ERROR: Failed building wheel for python-djvulibre
  Running setup.py clean for python-djvulibre
Failed to build python-djvulibre
Installing collected packages: python-djvulibre
    Running setup.py install for python-djvulibre ... error
    ERROR: Command errored out with exit status 1:
     command: /home/matthew/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8xjtabd6/python-djvulibre/setup.py'"'"'; __file__='"'"'/tmp/pip-install-8xjtabd6/python-djvulibre/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ixv2wml8/install-record.txt --single-version-externally-managed --compile
         cwd: /tmp/pip-install-8xjtabd6/python-djvulibre/
    Complete output (47 lines):
    pkg-config failed: Package ddjvuapi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `ddjvuapi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'ddjvuapi' found
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/djvu
    copying djvu/__init__.py -> build/lib.linux-x86_64-3.7/djvu
    copying djvu/const.py -> build/lib.linux-x86_64-3.7/djvu
    copying djvu/dllpath.py -> build/lib.linux-x86_64-3.7/djvu
    running build_ext
    pkg-config failed: Package ddjvuapi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `ddjvuapi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'ddjvuapi' found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-8xjtabd6/python-djvulibre/setup.py", line 321, in <module>
        distutils.core.setup(**setup_params)
      File "/home/matthew/anaconda3/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/matthew/anaconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/matthew/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/matthew/anaconda3/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/matthew/anaconda3/lib/python3.7/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/home/matthew/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/matthew/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/matthew/anaconda3/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/home/matthew/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/matthew/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-8xjtabd6/python-djvulibre/setup.py", line 174, in run
        djvulibre_version = get_djvulibre_version()
      File "/tmp/pip-install-8xjtabd6/python-djvulibre/setup.py", line 140, in get_djvulibre_version
        raise RuntimeError('cannot determine DjVuLibre version')
    RuntimeError: cannot determine DjVuLibre version
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/matthew/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8xjtabd6/python-djvulibre/setup.py'"'"'; __file__='"'"'/tmp/pip-install-8xjtabd6/python-djvulibre/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ixv2wml8/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

**Comment by jwilk** [comment]
>```
>  pkg-config failed: Package ddjvuapi was not found in the pkg-config search path.
>  Perhaps you should add the directory containing `ddjvuapi.pc'
>  to the PKG_CONFIG_PATH environment variable
>```
Looks like DjVuLibre development files are not installed; or they are installed in a non-standard directory, so pkg-config can't find them.

**Comment by weiss-d** [comment]
Same problem on Pop!_OS 20.04:

```
$ pip3 install python-djvulibre
Collecting python-djvulibre
  Using cached python-djvulibre-0.8.5.tar.gz (87 kB)
Building wheels for collected packages: python-djvulibre
  Building wheel for python-djvulibre (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/weissd/.pyenv/versions/3.8.5/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-xwhiixht/python-djvulibre/setup.py'"'"'; __file__='"'"'/tmp/pip-install-xwhiixht/python-djvulibre/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-zgqs2kti
       cwd: /tmp/pip-install-xwhiixht/python-djvulibre/
  Complete output (45 lines):
  pkg-config failed: Package ddjvuapi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `ddjvuapi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'ddjvuapi' found
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  creating build/lib.linux-x86_64-3.8/djvu
  copying djvu/__init__.py -> build/lib.linux-x86_64-3.8/djvu
  copying djvu/const.py -> build/lib.linux-x86_64-3.8/djvu
  copying djvu/dllpath.py -> build/lib.linux-x86_64-3.8/djvu
  running build_ext
  pkg-config failed: Package ddjvuapi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `ddjvuapi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'ddjvuapi' found
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-xwhiixht/python-djvulibre/setup.py", line 321, in <module>
      distutils.core.setup(**setup_params)
    File "/home/weissd/.pyenv/versions/3.8.5/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/weissd/.pyenv/versions/3.8.5/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/home/weissd/.pyenv/versions/3.8.5/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/weissd/.pyenv/versions/3.8.5/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 290, in run
      self.run_command('build')
    File "/home/weissd/.pyenv/versions/3.8.5/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/weissd/.pyenv/versions/3.8.5/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/weissd/.pyenv/versions/3.8.5/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/weissd/.pyenv/versions/3.8.5/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/weissd/.pyenv/versions/3.8.5/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-xwhiixht/python-djvulibre/setup.py", line 174, in run
      djvulibre_version = get_djvulibre_version()
    File "/tmp/pip-install-xwhiixht/python-djvulibre/setup.py", line 140, in get_djvulibre_version
      raise RuntimeError('cannot determine DjVuLibre version')
  RuntimeError: cannot determine DjVuLibre version
  ----------------------------------------
  ERROR: Failed building wheel for python-djvulibre
  Running setup.py clean for python-djvulibre
Failed to build python-djvulibre
DEPRECATION: Could not build wheels for python-djvulibre which do not use PEP 517. pip will fall back to legacy 'setup.py install' for these. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
Installing collected packages: python-djvulibre
    Running setup.py install for python-djvulibre ... error
    ERROR: Command errored out with exit status 1:
     command: /home/weissd/.pyenv/versions/3.8.5/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-xwhiixht/python-djvulibre/setup.py'"'"'; __file__='"'"'/tmp/pip-install-xwhiixht/python-djvulibre/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-x6_5jd88/install-record.txt --single-version-externally-managed --compile --install-headers /home/weissd/.pyenv/versions/3.8.5/include/python3.8/python-djvulibre
         cwd: /tmp/pip-install-xwhiixht/python-djvulibre/
    Complete output (47 lines):
    pkg-config failed: Package ddjvuapi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `ddjvuapi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'ddjvuapi' found
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    creating build/lib.linux-x86_64-3.8/djvu
    copying djvu/__init__.py -> build/lib.linux-x86_64-3.8/djvu
    copying djvu/const.py -> build/lib.linux-x86_64-3.8/djvu
    copying djvu/dllpath.py -> build/lib.linux-x86_64-3.8/djvu
    running build_ext
    pkg-config failed: Package ddjvuapi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `ddjvuapi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'ddjvuapi' found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-xwhiixht/python-djvulibre/setup.py", line 321, in <module>
        distutils.core.setup(**setup_params)
      File "/home/weissd/.pyenv/versions/3.8.5/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/weissd/.pyenv/versions/3.8.5/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/weissd/.pyenv/versions/3.8.5/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/weissd/.pyenv/versions/3.8.5/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/weissd/.pyenv/versions/3.8.5/lib/python3.8/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/home/weissd/.pyenv/versions/3.8.5/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/weissd/.pyenv/versions/3.8.5/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/weissd/.pyenv/versions/3.8.5/lib/python3.8/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/home/weissd/.pyenv/versions/3.8.5/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/weissd/.pyenv/versions/3.8.5/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-xwhiixht/python-djvulibre/setup.py", line 174, in run
        djvulibre_version = get_djvulibre_version()
      File "/tmp/pip-install-xwhiixht/python-djvulibre/setup.py", line 140, in get_djvulibre_version
        raise RuntimeError('cannot determine DjVuLibre version')
    RuntimeError: cannot determine DjVuLibre version
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/weissd/.pyenv/versions/3.8.5/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-xwhiixht/python-djvulibre/setup.py'"'"'; __file__='"'"'/tmp/pip-install-xwhiixht/python-djvulibre/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-x6_5jd88/install-record.txt --single-version-externally-managed --compile --install-headers /home/weissd/.pyenv/versions/3.8.5/include/python3.8/python-djvulibre Check the logs for full command output.
```

**Comment by maltaisn** [comment]
I had the same error on Ubuntu 20.04. There was no `ddjvuapi.pc` file in `/usr/share/pkg-config` as the error states. I tried building djvulibre from source but still there was no `ddjvuapi.pc` file at that location. In the end I did:
```
sudo apt install libdjvulibre-dev
dpkg-query -L libdjvulibre-dev | grep "ddjvuapi.pc" | sudo xargs cp -t /usr/share/pkgconfig/
```
`libdjvulibre-dev` has the `ddjvuapi.pc` file, which is then located with `dpkg-query` and copied to `/usr/share/pkgconfig/`.

**Comment by jwilk** [comment]
`/usr/share/pkgconfig/` is not the only directory where pkg-config looks for metadata files.
You can check what's the default search path like this:
```console
$ pkg-config --variable pc_path pkg-config
/usr/local/lib/x86_64-linux-gnu/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig
```

Manually copying the `.pc` files around is asking for trouble. Sooner or later they will get out of sync with the rest of the package.

Instead, as the error message says, use the `PKG_CONFIG_PATH` environment variable.

(FWIW, when I install `libdjvulibre-dev` on Ubuntu 20.04, pkg-config finds `ddjvuapi.pc` out of the box.)

**Comment by jwilk** [comment]
I've made a few changes to the build system that should reduce noise in error messages.
Hopefully that will make the important part easier to spot.
For the upcoming release, if you use pip ≥ 19.0, the failure should look like this:
```
Building wheels for collected packages: python-djvulibre
  Building wheel for python-djvulibre (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /home/jwilk/.local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpq28dhld0
       cwd: /tmp/pip-req-build-nqvmfunb
  Complete output (16 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/djvu
  copying djvu/__init__.py -> build/lib.linux-x86_64-3.7/djvu
  copying djvu/const.py -> build/lib.linux-x86_64-3.7/djvu
  copying djvu/dllpath.py -> build/lib.linux-x86_64-3.7/djvu
  running build_ext
  pkg-config failed:
    Package ddjvuapi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `ddjvuapi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'ddjvuapi' found
  error: cannot determine DjVuLibre version
  ----------------------------------------
  ERROR: Failed building wheel for python-djvulibre
Failed to build python-djvulibre
ERROR: Could not build wheels for python-djvulibre which use PEP 517 and cannot be installed directly
```

**Comment by huntekah** [comment]
**Easy solution for Arch Linux:**

I had this issue by installing DjVuLibre with 
`git clone https://github.com/DjvuNet/DjVuLibre.git && cd DjVuLibre && autogen.sh && make && sudo make install`

So I uninstalled it:
`sudo make uninstall`

and the following commands worked like a charm:
`sudo pacman -S djvulibre`
`pip install python-djvulibre`

**Comment by jwilk** [comment]
> I've made a few changes to the build system that should reduce noise in error messages.

I've just released [0.8.6](https://pypi.org/project/python-djvulibre/0.8.6/) with these fixes included.
Let me know if there's anything else that could be improved further.

**Comment by xqt** [comment]
I got this error when trying to install with Python 3.10.2
```
C:\pwb\GIT\core>pip install python-djvulibre
Collecting python-djvulibre
  Downloading python-djvulibre-0.8.7.tar.gz (87 kB)
     ---------------------------------------- 87.8/87.8 KB 1.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: python-djvulibre
  Building wheel for python-djvulibre (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for python-djvulibre (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      setup.py:159: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        return distutils.version.LooseVersion(ver)
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.10
      creating build\lib.win-amd64-3.10\djvu
      copying djvu\__init__.py -> build\lib.win-amd64-3.10\djvu
      copying djvu\const.py -> build\lib.win-amd64-3.10\djvu
      copying djvu\dllpath.py -> build\lib.win-amd64-3.10\djvu
      running build_ext
      cannot execute pkg-config: Das System kann die angegebene Datei nicht finden
      setup.py:146: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        return distutils.version.LooseVersion(version)
      cannot execute pkg-config: Das System kann die angegebene Datei nicht finden
      creating build\temp.win-amd64-3.10
      creating build\temp.win-amd64-3.10\Release
      creating build\temp.win-amd64-3.10\Release\src
      creating 'build\\temp.win-amd64-3.10\\Release\\src\\config.pxi'
      cythoning 'djvu.decode' extension
      generating build\temp.win-amd64-3.10\Release\src\decode.c from djvu/decode.pyx, build\temp.win-amd64-3.10\Release\src\config.pxi, djvu/common.pxi, djvu\decode.pxd, djvu\sexpr.pxd
      C:\Python310\python.exe -m cython -I build\temp.win-amd64-3.10\Release\src -o build\temp.win-amd64-3.10\Release\src\decode.c djvu/decode.pyx
      warning: djvu\common.pxi:139:4: Exception already a builtin Cython type
      building 'djvu.decode' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for python-djvulibre
Failed to build python-djvulibre
ERROR: Could not build wheels for python-djvulibre, which is required to install pyproject.toml-based projects
```

Microsoft Visual C++ 2015 Resdistributal - 14.26.29325 and 14.26.28720 are installed
